### ISSUE TITLE
Vale is picking up errors for stuff in code blocks in GitHub markdown

### ISSUE THREAD

**Issue by ramyaparimi** [errata-ai/vale#387]
- OS: macOS
- Install method: Homebrew
- vale version 2.11.2

Here is my `.vale.ini`

```
StylesPath = vale

# suggestion, warning or error
MinAlertLevel = warning 

Vocab = Docs

IgnoredScopes = code,tt, em

[*.md]
BasedOnStyles = Vale,Vocab

TokenIgnores = \(\/.*?\), \
               {%.*?%}, \
               {{.*?}}, \
               (.|\/|-)?github(\/|-)?, \
               (<http[^\n]+>+?)
```

There are the types of errors it is picking up:

`content/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions.md:152:53:Vale.Terms:Use 'hostname' instead of 'HOSTNAME'.`
`
<img width="835" alt="image" src="https://user-images.githubusercontent.com/33761166/145460369-14e10663-219f-4d3a-900d-7c56fb738624.png">

`content/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions.md:236:21:Vale.Terms:Use 'npm' instead of 'NPM'.`

<img width="487" alt="image" src="https://user-images.githubusercontent.com/33761166/145460429-f08204cf-2cbb-44ab-ba01-e6a6e9c57d5c.png">

Not sure what I am missing.

**Comment by jdkato** [comment]
Assuming that [this](https://github.com/github/docs/blob/main/content/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions.md) is the file in question, you're not using a standard flavor of Markdown -- it looks like you're making significant use of Liquid-like template tags along with mixing nested Markdown inside raw HTML.

This means that, as you've seen, there's no guarantee that Vale will be able to correctly parse and lint your content (GitHub itself, as you can see in the file preview I linked above, cannot render it correctly).

It's possible to work around these issues by using a combination of `BlockIgnores` and `TokenIgnores`, but it's not necessarily straightforward.

Another option would be to run Vale on your site's generated HTML, which should just work as you'd expect.

**Comment by ramyaparimi** [comment]
Thanks so much for answering my question. It all makes sense now. I will try running Vale on site generated HTML. 

Considering this scenario, will I be able to use [Vale Action to run only on lines modified in a PR](https://github.com/errata-ai/vale-action#onlyannotatemodifiedlines-default-false)s? I am assuming that would work as expected if the modified lines do not have the Liquid like templates 😞

**Comment by ramyaparimi** [comment]
I added a regular expression to BlockIgnores and TokenIgnores to avoid code blocks! Seems like it is not picking up things from code blocks and errors. This is how my `.vale.ini` looks now.

```
StylesPath = vale

# suggestion, warning or error
MinAlertLevel = warning 

Vocab = Docs

IgnoredScopes = code,tt, em, link, blockquote

[*.md]
BasedOnStyles = Vale,Vocab

BlockIgnores = ```[a-z]*[\s\S]*?\n```

TokenIgnores = \(\/.*?\), \
               {%.*?%}, \
               {{.*?}}, \
               (.|\/|-)?github(\/|-)?, \
               (<http[^\n]+>+?), \
               (```[a-z]*[\s\S]*?\n```)
```

**Comment by ramyaparimi** [comment]
I used this regex in TokenIgnores to for code blocks so Vale can ignore them. Vale is still picking up terms from code blocks. Not sure if I am missing something. Here is my .vale.ini

```
[*.md]
BasedOnStyles = Vale,Vocab

BlockIgnores = ```[a-z]*[\s\S]*?\n```

TokenIgnores = \(\/.*?\), \
               {%.*?%}, \
               {{.*?}}, \
               (.|\/|-)?github(\/|-)?, \
               (<http[^\n]+>+?), \
               (```[a-z]*[\s\S]*?\n```), \
               `[a-z]*[\s\S]*?`, \
               \[([^\[]+)\]\((.*)\)
```
- Here is the [regex101](https://regex101.com/r/TW3zo2/1/) where it is showing a match to code block
- Here is my error:
[content/actions/learn-github-actions/workflow-commands-for-github-actions.md:324:20:Vale.Spelling:Did you really mean 'mypath'?](https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#environment-files)
[content/actions/learn-github-actions/workflow-commands-for-github-actions.md:324:50:Vale.Spelling:Did you really mean 'env'?](https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#environment-files)

**Comment by jdkato** [comment]
> Not sure if I am missing something.

Yes, I'd like to make something clear: the behavior you're experiencing *is not a bug* with Vale.

I cannot emphasize enough that I think you'd be better off running Vale on the HTML generated by whatever you use to build your site.

The problem, as I mentioned in my previous comment, is that your content is different enough from CommonMark that Markdown assumptions (like ignoring code blocks) no longer apply. 

---

More specifically, your regex doesn't match what you appear to think it matches. If you test against the entire file (or a significant portion) in regex101, you'll quickly see that this is the case.

Additionally, the goal with `BlockIgnores` and `TokenIgnores` is to ignore non-standard markup syntax that interferes with Vale's parsing of the file; not known constructs like backtick-delimited code blocks. When you look at a file preview from GitHub ([like this](https://github.com/github/docs/blob/main/content/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions.md)), the parts that are rendered incorrectly are what you want to ignore.
