### ISSUE TITLE
TokenIgnores -- only one statement working at a time.

### ISSUE THREAD

**Issue by brest-amzn** [errata-ai/vale#389]
## Env 

Windows 
Vale Server 1.13.0
Atom

## Problem

Multiple TokenIgnore statements don't work when added to the Vale.ini. However, they work on their own.

For example, here is my config. In this case, Token1 works, but not Token2

```
StylesPath = "C:/Users/username/Desktop/styles"

[*.{md}]

# List of styles to load. 

BasedOnStyles =  warning, error

# Token1
TokenIgnores = (\{\% include user-speech-inline.html .*\%\})

# Token2
TokenIgnores = (\{\% include image.html .*\%\})
```

If I swap them... Token2 works, but Token1 stops working

```
StylesPath = "C:/Users/username/Desktop/styles"

[*.{md}]

# List of styles to load. 

BasedOnStyles =  warning, error

# Token2
TokenIgnores = (\{\% include image.html .*\%\})

# Token1
TokenIgnores = (\{\% include user-speech-inline.html .*\%\})

```

## Reference

Example screenshots

![test-case-1](https://user-images.githubusercontent.com/55214086/145652567-aa398ede-521d-46f2-926c-d95764c1c2b2.JPG)

![test-case-2](https://user-images.githubusercontent.com/55214086/145652576-384819ce-5b99-4e32-a817-2f0ec10beeb7.JPG)

Text used 

```
## Test

Here is some text.  

{% include user-speech-inline.html content="Who is Suprman"%}

Here is some text.

{% include image.html file="filepath" type="png" max-width="90%" url="https://myfile.com" border="true" %}
```

**Comment by jdkato** [comment]
You need to define `TokenIgnores` only once:

```ini
TokenIgnores = (\{\% include image.html .*\%\}), \
(\{\% include user-speech-inline.html .*\%\})
```

The patterns should be comma-delimited and newlines should be escaped with `\` (as shown above).
