### ISSUE TITLE
Problem with downloading readability package

### ISSUE THREAD

**Issue by thornycrackers** [errata-ai/vale#440]
```
Packages = Microsoft, readability

[*]
BasedOnStyles = Vale, Microsoft, readability
```

This is a sample that I pulled from the config generator. When I tried to execute `vale sync` I got the issue:

```
Get "readability": unsupported protocol scheme ""
```

I looked at the repo https://github.com/errata-ai/readability which has the folder as `Readability` with a capital R. I updated my config to have the capital 'R' and everything worked correctly. I don't know where in the chain is the correct fix but if others run into this issue I wanted to provide a solution.

**Comment by jdkato** [comment]
Thanks for the report. I generator has been updated.
